FROM python:3.10-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt -i https://mirror.yandex.ru/pypi/simple/
# Копируем весь код
COPY . .

# Порт, который слушает aiohttp (должен совпадать с WEBHOOK_PORT)
EXPOSE 8080

# Запуск вашего main.py
CMD ["python", "main.py"]